### ISSUE TITLE
Road

### ISSUE THREAD

**Issue by semjon00** [semjon00/MomentumRacing#2]
In the end, we should have some sort of a road. If ship is not on a road, it will lose speed until it reaches some small value.

**Comment by lauri0** [comment]
I'd recommend going for some checkpoints around a few houses first. Actual road could be one of the later things we work on imo.

**Comment by semjon00** [comment]
Now it is implemented in 02da7a572d6484d15f53e77e2a331b0f441eb535.

**Comment by semjon00** [comment]
This might be helpfull:
https://www.youtube.com/watch?v=7YUxM0NDWRY

**Comment by semjon00** [comment]
Initial progress in 6f65f7934fe43f0ba97cd6ccf2cc8752e1275446.

**Comment by semjon00** [comment]
Please use RoadMesh to create a better road, use Alt to draw more efficiently.

**Comment by semjon00** [comment]
Should be smoother and wider.

**Comment by semjon00** [comment]
Fix: world coordinates
